info: Server started at http://localhost:4000/api/v1/ {"timestamp":"2022-11-11T18:41:09.507Z"}
info: Connected to the database. {"timestamp":"2022-11-11T18:41:09.573Z"}
error: 
    status - 500 
    message - ReferenceError: res is not defined
    at _callee5$ (E:\fundo-project\fundoo\src\services\/user.service.js:40:12)
    at tryCatch (E:\fundo-project\fundoo\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (E:\fundo-project\fundoo\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (E:\fundo-project\fundoo\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (E:\fundo-project\fundoo\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\fundo-project\fundoo\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-11-11T18:41:22.669Z"}
error: 
    status - 500 
    message - ReferenceError: res is not defined
    at _callee5$ (E:\fundo-project\fundoo\src\services\/user.service.js:40:12)
    at tryCatch (E:\fundo-project\fundoo\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (E:\fundo-project\fundoo\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (E:\fundo-project\fundoo\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (E:\fundo-project\fundoo\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\fundo-project\fundoo\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-11-11T18:41:30.789Z"}
info: Server started at http://localhost:4000/api/v1/ {"timestamp":"2022-11-11T18:42:57.583Z"}
info: Connected to the database. {"timestamp":"2022-11-11T18:42:57.763Z"}
error: 
    status - 500 
    message - ReferenceError: res is not defined
    at _callee5$ (E:\fundo-project\fundoo\src\services\/user.service.js:40:12)
    at tryCatch (E:\fundo-project\fundoo\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (E:\fundo-project\fundoo\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (E:\fundo-project\fundoo\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (E:\fundo-project\fundoo\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\fundo-project\fundoo\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-11-11T18:43:02.772Z"}
error: 
    status - 500 
    message - ReferenceError: res is not defined
    at _callee5$ (E:\fundo-project\fundoo\src\services\/user.service.js:40:12)
    at tryCatch (E:\fundo-project\fundoo\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (E:\fundo-project\fundoo\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (E:\fundo-project\fundoo\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (E:\fundo-project\fundoo\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\fundo-project\fundoo\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-11-11T18:43:10.771Z"}
info: Server started at http://localhost:4000/api/v1/ {"timestamp":"2022-11-11T19:01:25.520Z"}
info: Connected to the database. {"timestamp":"2022-11-11T19:01:25.622Z"}
info: Server started at http://localhost:4000/api/v1/ {"timestamp":"2022-11-11T19:02:23.184Z"}
info: Connected to the database. {"timestamp":"2022-11-11T19:02:23.261Z"}
info: Server started at http://localhost:4000/api/v1/ {"timestamp":"2022-11-11T19:28:28.941Z"}
info: Connected to the database. {"timestamp":"2022-11-11T19:28:28.991Z"}
info: Server started at http://localhost:4000/api/v1/ {"timestamp":"2022-11-11T19:30:24.421Z"}
info: Connected to the database. {"timestamp":"2022-11-11T19:30:24.462Z"}
info: Server started at http://localhost:4000/api/v1/ {"timestamp":"2022-11-11T19:31:18.476Z"}
info: Connected to the database. {"timestamp":"2022-11-11T19:31:18.516Z"}
info: Server started at http://localhost:4000/api/v1/ {"timestamp":"2022-11-11T19:32:32.529Z"}
info: Connected to the database. {"timestamp":"2022-11-11T19:32:32.577Z"}
info: Server started at http://localhost:4000/api/v1/ {"timestamp":"2022-11-11T19:40:17.130Z"}
info: Connected to the database. {"timestamp":"2022-11-11T19:40:17.176Z"}
error: 
    status - 500 
    message - SyntaxError: Unexpected token } in JSON at position 60
    at JSON.parse (<anonymous>)
    at parse (E:\fundo-project\fundoo\node_modules\body-parser\lib\types\json.js:89:19)
    at E:\fundo-project\fundoo\node_modules\body-parser\lib\read.js:128:18
    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)
    at invokeCallback (E:\fundo-project\fundoo\node_modules\raw-body\index.js:231:16)
    at done (E:\fundo-project\fundoo\node_modules\raw-body\index.js:220:7)
    at IncomingMessage.onEnd (E:\fundo-project\fundoo\node_modules\raw-body\index.js:280:7)
    at IncomingMessage.emit (node:events:525:35)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1358:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) 
    url - /api/v1/users/ 
    method - GET 
    IP - ::1
   {"timestamp":"2022-11-11T19:40:55.764Z"}
