info: Server started at http://localhost:4000/api/v1/ {"timestamp":"2022-11-21T07:01:56.346Z"}
info: Connected to the database. {"timestamp":"2022-11-21T07:01:56.399Z"}
error: 
    status - 500 
    message - Error: data and hash arguments required
    at Object.compare (E:\fundo-project\fundoo-notes\node_modules\bcrypt\bcrypt.js:208:17)
    at E:\fundo-project\fundoo-notes\node_modules\bcrypt\promises.js:29:12
    at new Promise (<anonymous>)
    at Object.module.exports.promise (E:\fundo-project\fundoo-notes\node_modules\bcrypt\promises.js:20:12)
    at Object.compare (E:\fundo-project\fundoo-notes\node_modules\bcrypt\bcrypt.js:204:25)
    at _callee2$ (E:\fundo-project\fundoo-notes\src\services\/user.service.js:20:33)
    at tryCatch (E:\fundo-project\fundoo-notes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (E:\fundo-project\fundoo-notes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (E:\fundo-project\fundoo-notes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (E:\fundo-project\fundoo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\fundo-project\fundoo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/forgotpwd 
    method - POST 
    IP - ::1
   {"timestamp":"2022-11-21T07:02:30.311Z"}
info: Server started at http://localhost:4000/api/v1/ {"timestamp":"2022-11-21T07:05:20.474Z"}
info: Connected to the database. {"timestamp":"2022-11-21T07:05:20.520Z"}
error: 
    status - 500 
    message - Error: Invalid Email
    at _callee3$ (E:\fundo-project\fundoo-notes\src\services\/user.service.js:41:11)
    at tryCatch (E:\fundo-project\fundoo-notes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (E:\fundo-project\fundoo-notes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (E:\fundo-project\fundoo-notes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (E:\fundo-project\fundoo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\fundo-project\fundoo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/forgotpwd 
    method - POST 
    IP - ::1
   {"timestamp":"2022-11-21T07:05:52.308Z"}
info: Server started at http://localhost:4000/api/v1/ {"timestamp":"2022-11-21T07:07:23.328Z"}
info: Connected to the database. {"timestamp":"2022-11-21T07:07:23.369Z"}
info: Server started at http://localhost:4000/api/v1/ {"timestamp":"2022-11-21T07:50:27.941Z"}
info: Connected to the database. {"timestamp":"2022-11-21T07:50:27.986Z"}
info: Server started at http://localhost:4000/api/v1/ {"timestamp":"2022-11-21T07:51:29.545Z"}
info: Connected to the database. {"timestamp":"2022-11-21T07:51:29.596Z"}
info: Server started at http://localhost:4000/api/v1/ {"timestamp":"2022-11-21T07:52:00.279Z"}
info: Connected to the database. {"timestamp":"2022-11-21T07:52:00.322Z"}
error: 
    status - 500 
    message - Error: Invalid Password
    at _callee2$ (E:\fundo-project\fundoo-notes\src\services\/user.service.js:27:13)
    at tryCatch (E:\fundo-project\fundoo-notes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (E:\fundo-project\fundoo-notes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (E:\fundo-project\fundoo-notes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (E:\fundo-project\fundoo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\fundo-project\fundoo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9) 
    url - /api/v1/users/login 
    method - POST 
    IP - ::1
   {"timestamp":"2022-11-21T07:54:28.883Z"}
info: Server started at http://localhost:4000/api/v1/ {"timestamp":"2022-11-21T07:59:48.918Z"}
info: Connected to the database. {"timestamp":"2022-11-21T07:59:48.966Z"}
info: Server started at http://localhost:4000/api/v1/ {"timestamp":"2022-11-21T08:01:10.205Z"}
info: Connected to the database. {"timestamp":"2022-11-21T08:01:10.256Z"}
info: Server started at http://localhost:4000/api/v1/ {"timestamp":"2022-11-21T08:05:26.564Z"}
info: Connected to the database. {"timestamp":"2022-11-21T08:05:26.644Z"}
info: Server started at http://localhost:4000/api/v1/ {"timestamp":"2022-11-21T08:10:18.645Z"}
info: Connected to the database. {"timestamp":"2022-11-21T08:10:18.694Z"}
info: Server started at http://localhost:4000/api/v1/ {"timestamp":"2022-11-21T08:11:57.545Z"}
info: Connected to the database. {"timestamp":"2022-11-21T08:11:57.599Z"}
info: Server started at http://localhost:4000/api/v1/ {"timestamp":"2022-11-21T08:13:42.110Z"}
info: Connected to the database. {"timestamp":"2022-11-21T08:13:42.163Z"}
error: 
    status - 500 
    message - ReferenceError: newPassword is not defined
    at _callee4$ (E:\fundo-project\fundoo-notes\src\services\/user.service.js:53:14)
    at tryCatch (E:\fundo-project\fundoo-notes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (E:\fundo-project\fundoo-notes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (E:\fundo-project\fundoo-notes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (E:\fundo-project\fundoo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\fundo-project\fundoo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at E:\fundo-project\fundoo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:27:7
    at new Promise (<anonymous>)
    at Object.<anonymous> (E:\fundo-project\fundoo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:19:12)
    at Object.resetPassword (E:\fundo-project\fundoo-notes\src\services\/user.service.js:49:27)
    at _callee4$ (E:\fundo-project\fundoo-notes\src\controllers\/user.controller.js:69:36)
    at tryCatch (E:\fundo-project\fundoo-notes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (E:\fundo-project\fundoo-notes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (E:\fundo-project\fundoo-notes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (E:\fundo-project\fundoo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\fundo-project\fundoo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at E:\fundo-project\fundoo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:27:7
    at new Promise (<anonymous>)
    at E:\fundo-project\fundoo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:19:12
    at resetPassword (E:\fundo-project\fundoo-notes\src\controllers\/user.controller.js:67:28)
    at Layer.handle [as handle_request] (E:\fundo-project\fundoo-notes\node_modules\express\lib\router\layer.js:95:5)
    at next (E:\fundo-project\fundoo-notes\node_modules\express\lib\router\route.js:144:13)
    at _callee$ (E:\fundo-project\fundoo-notes\src\middlewares\/auth.middleware.js:26:5)
    at tryCatch (E:\fundo-project\fundoo-notes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (E:\fundo-project\fundoo-notes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (E:\fundo-project\fundoo-notes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (E:\fundo-project\fundoo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\fundo-project\fundoo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/users/resetpwd 
    method - PUT 
    IP - ::1
   {"timestamp":"2022-11-21T08:13:56.739Z"}
info: Server started at http://localhost:4000/api/v1/ {"timestamp":"2022-11-21T08:14:22.562Z"}
info: Connected to the database. {"timestamp":"2022-11-21T08:14:22.611Z"}
info: Server started at http://localhost:4000/api/v1/ {"timestamp":"2022-11-21T08:17:47.176Z"}
info: Connected to the database. {"timestamp":"2022-11-21T08:17:47.232Z"}
info: Server started at http://localhost:4000/api/v1/ {"timestamp":"2022-11-21T08:19:49.761Z"}
info: Connected to the database. {"timestamp":"2022-11-21T08:19:49.815Z"}
info: Server started at http://localhost:4000/api/v1/ {"timestamp":"2022-11-21T08:27:20.309Z"}
info: Connected to the database. {"timestamp":"2022-11-21T08:27:20.353Z"}
info: Server started at http://localhost:4000/api/v1/ {"timestamp":"2022-11-21T09:14:25.475Z"}
info: Connected to the database. {"timestamp":"2022-11-21T09:14:25.527Z"}
info: Server started at http://localhost:4000/api/v1/ {"timestamp":"2022-11-21T09:17:17.845Z"}
info: Connected to the database. {"timestamp":"2022-11-21T09:17:17.892Z"}
info: Server started at http://localhost:4000/api/v1/ {"timestamp":"2022-11-21T09:18:33.402Z"}
info: Connected to the database. {"timestamp":"2022-11-21T09:18:33.459Z"}
error: 
    status - 500 
    message - ValidationError: "firstname" is required 
    url - /api/v1/users/register 
    method - POST 
    IP - ::1
   {"timestamp":"2022-11-21T09:21:31.857Z"}
error: 
    status - 500 
    message - ValidationError: "lastname" length must be at least 4 characters long 
    url - /api/v1/users/register 
    method - POST 
    IP - ::1
   {"timestamp":"2022-11-21T09:22:59.473Z"}
info: Server started at http://localhost:4000/api/v1/ {"timestamp":"2022-11-21T09:25:30.062Z"}
info: Connected to the database. {"timestamp":"2022-11-21T09:25:30.113Z"}
info: Server started at http://localhost:4000/api/v1/ {"timestamp":"2022-11-21T11:44:14.388Z"}
info: Connected to the database. {"timestamp":"2022-11-21T11:44:14.498Z"}
info: Server started at http://localhost:4000/api/v1/ {"timestamp":"2022-11-21T11:49:56.352Z"}
info: Connected to the database. {"timestamp":"2022-11-21T11:49:56.396Z"}
error: 
    status - 500 
    message - Error: No note is available with this userID
    at _callee2$ (E:\fundo-project\fundoo-notes\src\services\/notes.service.js:16:15)
    at tryCatch (E:\fundo-project\fundoo-notes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:44:17)
    at Generator.<anonymous> (E:\fundo-project\fundoo-notes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:125:22)
    at Generator.next (E:\fundo-project\fundoo-notes\node_modules\@babel\runtime\helpers\regeneratorRuntime.js:69:21)
    at asyncGeneratorStep (E:\fundo-project\fundoo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:3:24)
    at _next (E:\fundo-project\fundoo-notes\node_modules\@babel\runtime\helpers\asyncToGenerator.js:22:9)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) 
    url - /api/v1/notes/ 
    method - GET 
    IP - ::1
   {"timestamp":"2022-11-21T13:02:27.969Z"}
info: Server started at http://localhost:4000/api/v1/ {"timestamp":"2022-11-21T13:06:07.253Z"}
info: Connected to the database. {"timestamp":"2022-11-21T13:06:07.293Z"}
info: Server started at http://localhost:4000/api/v1/ {"timestamp":"2022-11-21T16:21:37.326Z"}
info: Connected to the database. {"timestamp":"2022-11-21T16:21:37.367Z"}
